--- #YAML:1.0
name:               URI-ParseSearchString
version:            3.44
abstract:           parse search engine referrer URLs and extract keywords used
author:
    - Spiros Denaxas <spiros@lokku.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:        0
    Test::NoWarnings:  0
    URI:               0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
